### ISSUE TITLE
[FR] Verification check for service creation arguments

### ISSUE THREAD

**Issue by ElsaChelala** [cloudfoundry/csb-brokerpak-azure#556]
**Is your feature request related to a problem? Please describe.**

Currently, when creating a service using the Cloud Service Broker, there is no verification check for the arguments passed. This leads to situations where the database gets created but raises an error with Terraform, preventing further operations. 

Server error, status code: 502, error code: 10001, message: Service Instance test: Service broker error: failed to delete: workspace not generated

They then have to submit a ticket to our our platform operation team in order to have them purge the instance from the broker to then delete the service. 

**To reproduce**

Steps to reproduce the behaviour

1. Create an azure SQL database service instance, with a non-existing server. 
2. Attempt the delete the service instance.

**Describe the solution you'd like**

I suggest implementing a verification check for the arguments passed in the service creation process. This check should ensure that the specified servers exist, are in the correct subscription, and that the server pair name exists and is correct. 

If the arguments are not correct, the database creation should be aborted, preventing the error from occurring.

Additionally, a nice to have would be to link each organization to their respective servers, allowing them to view the servers in a table display.

**Additional context**
This situation occurs when using the CF CLI or the app manager.

**Comment by pivotal-marcela-campo** [comment]
Hi @ElsaChelala , thanks for raising this with us. It is indeed not validated at the moment. We'll take a look at prioritising this although I don't think we'll get to this any time soon.
We are open for contributions though. It looks like validations that could be achieved with terraform pre/post conditions. If you are willing to submit a PR, please reach out so we can point you to examples were we have implemented validations and their corresponding tests.

**Comment by pivotal-marcela-campo** [comment]
Hi @ElsaChelala, discussing internally with the team, we realised that even in the case where the validation is implemented, the issue with having to purge the service instance would still persist and all you'd get is an improved error message.
This would entail changes in the broker itself to either store the workspace regardless or clean up after a failure. Storing the workspace regardless of an error would probably not fix this issue either as the same error in validation would most probably happen when trying to destroy.
The issue of cleaning up in the face of an error is a more complex one that is not currently in our roadmap for the foreseeable future. 
The reason for returning an error and pointing to the operator is that in the general case of an error in any service in any brokerpak, we cannot at the moment ensure that no infrastructure has been created and it might need manual cleanup from the IaaS. 

In this scenario, there shouldn't be any infrastructure created on the IaaS based on [this code](https://github.com/cloudfoundry/csb-brokerpak-azure/blob/main/terraform/azure-mssql-db/provision/mssql-db-data.tf), as failure to retrieve the server will result in a failure in terraform before it creates any infrastructure. The instance, however, will already have a reference in the cloud controller database and therefore will need to be cleaned up. This can be achieve by running

`cf purge-service-instance <instance_name>`

**Comment by pivotal-marcela-campo** [comment]
closing per lack of activity
