### ISSUE TITLE
[FR] Ability to set individual timeout for errand deploy-all

### ISSUE THREAD

**Issue by ElsaChelala** [cloudfoundry/csb-brokerpak-azure#557]
**Is your feature request related to a problem? Please describe.**
Although the timeout value was recently increased from 60 to 120 seconds, we have noticed that the errand `deploy-all` takes longer than 120 seconds to complete in our environment. This results in the errand timing out, and we are unable to overwrite the timeout value specified in the manifest.

**Describe the solution you'd like**
We suggest adding a feature that allows individuals to set their own timeout values in Ops Manager or a similar configuration interface. This way, each person can customize the timeout according to their specific environment and requirements. By providing this flexibility, users can prevent timeouts and successfully complete the `deploy-all` errand.

**Describe alternatives you've considered**
If the latter is not possible, increasing the timeout value to 5 minutes should allow for the errand to run without interruption on our environment. 

**Additional context**
This situation occurs when using the CF CLI or the app manager.

**Comment by pivotal-marcela-campo** [comment]
Hi @ElsaChelala , the deploy-all errand is part of the VMWare Tile, proprietary tile that deploys the CSB for Azure broker. This repository is for the open source brokerpak which can only be deployed alongside the core broker using `cf push`. Your account team has been advised on how to direct this request through appropriate channels. 
Closing this issue.
Thanks
